### ISSUE TITLE
range out of index

### ISSUE THREAD

**Issue by sineptic** [CattoFace/aoc2024#2]
day 4 part 1

```
thread 'main' panicked at src/day4.rs:9:32:
range end index 19741 out of range for slice of length 19740
```

This affects all solutions of part 1 I think.

**Comment by barr-israel** [comment]
You have an edge case in your input that I don't have, where there is an X 2 bytes before the end of the file.  
I had an off by one error in one of the bound checks, fixed.  
Thanks for the report.
